name: Pre-commit

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        run: uv python install 3.11
      - name: Install venv
        run: uv venv
      - name: Install pre-commit
        run: uv pip install pre-commit
      - name: Run pre-commit
        run: uv run pre-commit run --all-files
